apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scaling-experiment
  name: scaling-experiment
spec:
  replicas:
    minimum: 5
    maximum: 50
  hpa:
    enabled: true
    cpuPercentage: 20
  compute_resources:
    enabled: true
    resources:
      requests:
        cpu: 1000m
        memory: 500m
      limits:
        cpu: 1000m
        memory: 500m
  selector:
    matchLabels:
      app: scaling-experiment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scaling-experiment
    spec:
      containers:
        - image: scaling-experiment
          name: scaling-experiment
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 8080
status: {}
