apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scaling-experiment
  name: scaling-experiment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-experiment
  strategy: {}
  template:
    metadata:
      labels:
        app: scaling-experiment
    spec:
      containers:
        - image: scaling-experiment
          name: scaling-experiment
          imagePullPolicy: Never
          resources:
            limits:
              memory: "50Mi"
              cpu: "20m"
            requests:
              memory: "50Mi"
              cpu: "20m"
          ports:
            - containerPort: 8080
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: scaling-experiment-service
spec:
  type: LoadBalancer
  selector:
    app: scaling-experiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-experiment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling-experiment
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
