apiVersion: v1
kind: Service
metadata:
  name: scaling-experiment-service
spec:
  type: LoadBalancer
  selector:
    app: scaling-experiment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
